/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rwp.invoice.generator.v1;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import jxl.read.biff.BiffException;
import jxl.write.WriteException;

/**
 *
 * @author rachelwhiting
 */
public class Invoice_genUI extends javax.swing.JFrame {
    
        public static boolean calculatedYet = false;

    /**
     * Creates new form NewJFrame
     */
    public Invoice_genUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        My_invoice_number = new javax.swing.JTextField();
        Refresh_invoice_number = new javax.swing.JTextField();
        Job_title = new javax.swing.JTextField();
        job_date = new javax.swing.JTextField();
        day_rate = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        number_of_days = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        assistant_rate = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        assistant_number_of_days = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        processing = new javax.swing.JTextField();
        Equipment = new javax.swing.JTextField();
        subsistence = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        client_name = new javax.swing.JTextField();
        Contact = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        rachel_total = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel18 = new javax.swing.JLabel();
        assistant_total = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        parking = new javax.swing.JTextField();
        congestion_charge = new javax.swing.JTextField();
        mileage = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        postage = new javax.swing.JTextField();
        generate_refresh_invoice = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        update_spreadsheet = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        total_extras = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        generate_my_invoice = new javax.swing.JButton();
        vat_total = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        calculate_totals = new javax.swing.JButton();
        total_due = new javax.swing.JTextField();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("My invoice number");

        jLabel2.setText("Refresh invoice number     RGW");

        jLabel3.setText("Job title");

        jLabel5.setText("Job date");

        jLabel6.setText("Day rate (£)");

        My_invoice_number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                My_invoice_numberActionPerformed(evt);
            }
        });

        Job_title.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Job_titleActionPerformed(evt);
            }
        });

        job_date.setText("dd/mm/yyyy");
        job_date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                job_dateActionPerformed(evt);
            }
        });

        day_rate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                day_rateActionPerformed(evt);
            }
        });

        jLabel4.setText("Number of days");

        number_of_days.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number_of_daysActionPerformed(evt);
            }
        });

        jLabel7.setText("Assistant rate (£)");

        assistant_rate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assistant_rateActionPerformed(evt);
            }
        });

        jLabel8.setText("Number of days");

        assistant_number_of_days.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assistant_number_of_daysActionPerformed(evt);
            }
        });

        jLabel9.setText("Processing (£)");

        jLabel10.setText("Equipment (£)");

        jLabel11.setText("Subsistence (£)");

        jLabel12.setText("Client name");

        jLabel13.setText("Contact");

        jLabel14.setText("Parking (£)");

        jLabel15.setText("Cong. Charge (£)");

        jLabel16.setText("Mileage (£)");

        jLabel17.setText("Total (£)");

        rachel_total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rachel_totalActionPerformed(evt);
            }
        });

        jLabel18.setText("Total (£)");

        assistant_total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assistant_totalActionPerformed(evt);
            }
        });

        jLabel19.setText("Postage (£)");

        generate_refresh_invoice.setText("Generate Refresh Invoice");
        generate_refresh_invoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generate_refresh_invoiceActionPerformed(evt);
            }
        });

        update_spreadsheet.setText("Update spreadsheet");
        update_spreadsheet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_spreadsheetActionPerformed(evt);
            }
        });

        jLabel20.setText("Total extras (£)");

        generate_my_invoice.setText("Generate my invoice");
        generate_my_invoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generate_my_invoiceActionPerformed(evt);
            }
        });

        vat_total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vat_totalActionPerformed(evt);
            }
        });

        jLabel21.setText("VAT total");

        jLabel22.setText("Total Due");

        calculate_totals.setText("Calculate totals");
        calculate_totals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculate_totalsActionPerformed(evt);
            }
        });

        total_due.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                total_dueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(9, 9, 9)
                        .addComponent(My_invoice_number, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Refresh_invoice_number, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Job_title)
                                    .addComponent(job_date, javax.swing.GroupLayout.DEFAULT_SIZE, 559, Short.MAX_VALUE)
                                    .addComponent(client_name)
                                    .addComponent(Contact)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(19, 19, 19)
                                        .addComponent(Equipment, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(congestion_charge, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel9)
                                                    .addComponent(jLabel19))
                                                .addGap(19, 19, 19)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(processing, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                                                    .addComponent(postage)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel11)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(subsistence)))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel16)
                                                .addGap(18, 18, 18)
                                                .addComponent(mileage))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel14)
                                                .addGap(17, 17, 17)
                                                .addComponent(parking, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel20)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(total_extras, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(36, 36, 36)
                                        .addComponent(total_due))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(197, 197, 197)
                                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 17, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(vat_total, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel22)
                                                .addGap(58, 58, 58))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel21)
                                                .addGap(59, 59, 59)))))))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(day_rate, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(number_of_days, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rachel_total))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(assistant_rate, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(assistant_number_of_days, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(assistant_total))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator6)
                            .addComponent(jSeparator4)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(648, 648, 648)
                                .addComponent(jSeparator3))
                            .addComponent(jSeparator1)
                            .addComponent(jSeparator2)
                            .addComponent(jSeparator5)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(calculate_totals, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(generate_my_invoice)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(generate_refresh_invoice, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(update_spreadsheet, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(My_invoice_number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Refresh_invoice_number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Job_title, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(job_date, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(client_name, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(Contact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(day_rate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(number_of_days, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(rachel_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(assistant_rate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(assistant_number_of_days, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(assistant_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(parking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel9)
                                .addComponent(processing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel14))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel21)))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(Equipment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)
                            .addComponent(congestion_charge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vat_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(subsistence, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel16)
                            .addComponent(mileage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(postage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20)
                            .addComponent(total_extras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(total_due, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(calculate_totals, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(update_spreadsheet, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(generate_refresh_invoice, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(generate_my_invoice, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addGap(110, 110, 110))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void My_invoice_numberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_My_invoice_numberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_My_invoice_numberActionPerformed

    private void day_rateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_day_rateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_day_rateActionPerformed

    private void number_of_daysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number_of_daysActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_number_of_daysActionPerformed

    private void Job_titleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Job_titleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Job_titleActionPerformed

    private void assistant_rateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assistant_rateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_assistant_rateActionPerformed

    private void assistant_number_of_daysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assistant_number_of_daysActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_assistant_number_of_daysActionPerformed

    private void rachel_totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rachel_totalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rachel_totalActionPerformed

    private void job_dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_job_dateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_job_dateActionPerformed

    private void assistant_totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assistant_totalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_assistant_totalActionPerformed

    private void generate_refresh_invoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generate_refresh_invoiceActionPerformed
        if (calculatedYet) {
            RFA_invoice_button.generate_RFA_invoice();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_generate_refresh_invoiceActionPerformed

    private void update_spreadsheetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_spreadsheetActionPerformed
        if (calculatedYet) {
            try {
                Excel_button.generate_Excel();
            } catch (IOException | BiffException | WriteException ex) {
                Logger.getLogger(Invoice_genUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_update_spreadsheetActionPerformed

    private void generate_my_invoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generate_my_invoiceActionPerformed
        if (calculatedYet) {
            RWP_invoice_button.generate_RWP_invoice();
        }
    }//GEN-LAST:event_generate_my_invoiceActionPerformed

    private void vat_totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vat_totalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vat_totalActionPerformed

    private void total_dueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_total_dueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_total_dueActionPerformed

    private void calculate_totalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculate_totalsActionPerformed
        
        //Populate text array from text fields of GUI
        Populate_text_array_from_GUI.Populate_0(Calculate_button.get_text(), this.getMyInvoiceNumber());
        Populate_text_array_from_GUI.Populate_1(Calculate_button.get_text(), this.getRefreshInvoiceNumber());
        Populate_text_array_from_GUI.Populate_4(Calculate_button.get_text(), this.getJobTitle());
        Populate_text_array_from_GUI.Populate_9(Calculate_button.get_text(), this.getJobDate());
        Populate_text_array_from_GUI.Populate_11(Calculate_button.get_text(), this.getDayRate());
        Populate_text_array_from_GUI.Populate_12(Calculate_button.get_text(), this.getNumberOfDays());
        Populate_text_array_from_GUI.Populate_14(Calculate_button.get_text(), this.getAssistantRate());
        Populate_text_array_from_GUI.Populate_15(Calculate_button.get_text(), this.getAssistantNumberOfDays());
        Populate_text_array_from_GUI.Populate_17(Calculate_button.get_text(), this.getRefreshInvoiceNumber());
        Populate_text_array_from_GUI.Populate_18(Calculate_button.get_text(), this.getClientName());
        Populate_text_array_from_GUI.Populate_19(Calculate_button.get_text(), this.getContact());
        Populate_text_array_from_GUI.Populate_20(Calculate_button.get_text(), this.getProcessing());
        Populate_text_array_from_GUI.Populate_23(Calculate_button.get_text(), this.getEquipment());
        Populate_text_array_from_GUI.Populate_26(Calculate_button.get_text(), this.getSubsistence());
        Populate_text_array_from_GUI.Populate_27(Calculate_button.get_text(), this.getParking());
        Populate_text_array_from_GUI.Populate_28(Calculate_button.get_text(), this.getCongestionCharge());
        Populate_text_array_from_GUI.Populate_29(Calculate_button.get_text(), this.getMileage());
        Populate_text_array_from_GUI.Populate_30(Calculate_button.get_text(), this.getPostage());
        
        //Sends array to calculation module to extract numbers and calculate totals
        Calculations.doCalculations(Calculate_button.get_text());
        
        //Repopulate text fields with Totals
        initArray text_array=Calculate_button.get_text();
        vat_total.setText(text_array.getInput(6));
        total_due.setText(text_array.getInput(7));
        rachel_total.setText(text_array.getInput(10));
        assistant_total.setText(text_array.getInput(13));
        total_extras.setText(text_array.getInput(16));
        
        //Allow invoices to be generated by other buttons
        calculatedYet = true;
    }//GEN-LAST:event_calculate_totalsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Invoice_genUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Invoice_genUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Invoice_genUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Invoice_genUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Invoice_genUI().setVisible(true);
            }
        });
    }
    

    // Set and Get
    public String getContact() {return Contact.getText();}
    public String getEquipment() {return Equipment.getText();}
    public String getJobTitle() {return Job_title.getText();}
    public String getMyInvoiceNumber() {return My_invoice_number.getText();}
    public String getRefreshInvoiceNumber() {return Refresh_invoice_number.getText();}
    public String getAssistantNumberOfDays() {return assistant_number_of_days.getText();}
    public String getAssistantRate() {return assistant_rate.getText();}
    public String getAssistantTotal() {return assistant_total.getText();}
    public String getClientName() {return client_name.getText();}
    public String getCongestionCharge() {return congestion_charge.getText();}
    public String getDayRate() {return day_rate.getText();}
    public String getJobDate() {return job_date.getText();}
    public String getMileage() {return mileage.getText();}
    public String getNumberOfDays() {return number_of_days.getText();}
    public String getParking() {return parking.getText();}
    public String getPostage() {return postage.getText();}
    public String getProcessing() {return processing.getText();}
    public String getRachelTotal() {return rachel_total.getText();}  
    public String getSubsistence() {return subsistence.getText();}
    public String getTotalDue() {return total_due.getText();}
    public String getTotalExtras() {return total_extras.getText();}
    public String getTotalVAT() {return vat_total.getText();}

    public void setAssistantTotal (String total) {assistant_total.setText(total);}
    public void setRachelTotal (String total) {rachel_total.setText(total);}
    public void setTotalDue (String total) {total_due.setText(total);}
    public void setTotalVAT (String total) {vat_total.setText(total);}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Contact;
    private javax.swing.JTextField Equipment;
    private javax.swing.JTextField Job_title;
    private javax.swing.JTextField My_invoice_number;
    private javax.swing.JTextField Refresh_invoice_number;
    private javax.swing.JTextField assistant_number_of_days;
    private javax.swing.JTextField assistant_rate;
    private javax.swing.JTextField assistant_total;
    private javax.swing.JButton calculate_totals;
    private javax.swing.JTextField client_name;
    private javax.swing.JTextField congestion_charge;
    private javax.swing.JTextField day_rate;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton generate_my_invoice;
    private javax.swing.JButton generate_refresh_invoice;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTextField job_date;
    private javax.swing.JTextField mileage;
    private javax.swing.JTextField number_of_days;
    private javax.swing.JTextField parking;
    private javax.swing.JTextField postage;
    private javax.swing.JTextField processing;
    private javax.swing.JTextField rachel_total;
    private javax.swing.JTextField subsistence;
    private javax.swing.JTextField total_due;
    private javax.swing.JTextField total_extras;
    private javax.swing.JButton update_spreadsheet;
    private javax.swing.JTextField vat_total;
    // End of variables declaration//GEN-END:variables
}

